name: Update Booking iCal (test)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Ogni 6 ore

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update file (ora italiana)
        run: |
          echo "BEGIN:VCALENDAR" > booking.txt
          echo "VEVENT: Test aggiornamento automatico $(TZ='Europe/Rome' date '+%a %b %d %H:%M:%S %Z %Y')" >> booking.txt
          echo "END:VCALENDAR" >> booking.txt

      - name: Commit e push aggiornamento
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add booking.txt
          git commit -m "Aggiornamento automatico test $(TZ='Europe/Rome' date '+%Y-%m-%d %H:%M:%S %Z')"
          git push
